apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rh-api-management/rhcl-file-based-catalog?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && (".tekton/rhcl-file-based-catalog-4-21-push.yaml".pathChanged() || ".tekton/fbc-build-pipeline.yaml".pathChanged() || "catalog/4.21.Containerfile".pathChanged() || "catalog/4.21/**".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rhcl-file-based-catalog
    appstudio.openshift.io/component: rhcl-file1-based-catalog-4-21
    pipelines.appstudio.openshift.io/type: build
  name: rhcl-file-based-catalog-4-21-on-push
  namespace: api-management-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/api-management-tenant/rhcl-file-based-catalog-4-21:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: catalog/4.21.Containerfile
  pipelineRef:
    name: fbc-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhcl-file-based-catalog-4-21
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
